site_name: ScanCode LicenseDB
site_url: http://localhost:8000
site_description: "A web interface to explore ScanCode license database"
site_author: "Your Name"

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Changelog: changelog.md